doris-vectorized/doris-vectorized

be/src/exec/exec_node.cpp
be/src/exec/olap_scan_node.cpp
be/src/vec/exec/aggregation_node.cpp

1. Support fitler conjunct push down to storage engine
2. Add Profile of VAGGREGATENODE

Support fitler conjunct push down to storage engine And Add Profile of VAGGREGATENODE

---

be/src/vec/exec/aggregation_node.cpp
be/src/vec/exec/aggregation_node.h
be/src/vec/exprs/vectorized_agg_fn.cpp

```
select sum(1) from table;
select sum(1) from table group by k1, k2;
```

[vectorized] support agg const

---

be/src/vec/CMakeLists.txt
be/src/vec/common/libdivide.h
be/src/vec/core/block.cpp
be/src/vec/core/block.h
be/src/vec/exec/olap_scan_node.cpp
be/src/vec/exprs/vexpr.cpp
be/src/vec/functions/divide.cpp
be/src/vec/functions/function_binary_arithmetic.h
be/src/vec/functions/int_div.cpp
be/src/vec/functions/int_div.h
be/src/vec/functions/minus.cpp
be/src/vec/functions/modulo.cpp
be/src/vec/functions/multiply.cpp
be/src/vec/functions/plus.cpp
be/src/vec/functions/simple_function_factory.h

RT
Change-Id: Ia2e7a23dc8b6cb4d643b9add05a866921c57e9f8

Support +=*/int_div operations and Support limit operation in volap_scan_node

---

be/src/vec/common/types.h
be/src/vec/core/block.cpp
be/src/vec/core/block.h
be/src/vec/core/field.cpp
be/src/vec/core/field.h
be/src/vec/core/types.h
be/src/vec/data_types/data_type.h
be/src/vec/data_types/data_type_nothing.cpp
be/src/vec/data_types/data_type_nothing.h
be/src/vec/data_types/data_type_nullable.cpp
be/src/vec/data_types/data_type_nullable.h
be/src/vec/data_types/data_type_number_base.cpp
be/src/vec/data_types/data_type_number_base.h
be/src/vec/data_types/data_type_string.cpp
be/src/vec/data_types/data_type_string.h
be/src/vec/data_types/data_types_decimal.cpp
be/src/vec/data_types/data_types_decimal.h
be/src/vec/data_types/data_types_number.h
be/src/vec/io/io_helper.h
be/src/vec/io/var_int.h
be/test/vec/core/block_test.cpp
gensrc/proto/data.proto

Support serialize and deserialize block

support serialize and deserialize block

---

be/src/vec/core/block.cpp
be/src/vec/data_types/data_type_nullable.cpp
be/src/vec/io/io_helper.h
be/test/vec/core/block_test.cpp

Fix core when serialize and deserialize nullable column

Fix core when serialize and deserialize nullable column

---

be/src/vec/data_types/data_type.cpp
be/src/vec/data_types/data_type.h
be/src/vec/data_types/data_type_nothing.cpp
be/src/vec/data_types/data_type_nothing.h
be/src/vec/data_types/data_type_nullable.cpp
be/src/vec/data_types/data_type_nullable.h
be/src/vec/data_types/data_type_number_base.cpp
be/src/vec/data_types/data_type_number_base.h
be/src/vec/data_types/data_type_string.cpp
be/src/vec/data_types/data_type_string.h
be/src/vec/data_types/data_types_decimal.cpp
be/src/vec/data_types/data_types_decimal.h

remove serialize function row by row
Change-Id: I1b97d0217b1fcd1647bd13a6565c6cce412e5a38
If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what …

remove serialize single row

---

fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java

Change avg intermediate type to origin type

Change avg intermediate type to origin type

---

be/src/vec/data_types/data_types_decimal.cpp
be/src/vec/exec/aggregation_node.cpp
be/src/vec/exec/aggregation_node.h

support multi-tablet no group AGG

[AGG] support multi-tablet no group AGG

---

be/src/exec/exec_node.cpp
be/src/exec/schema_scanner.cpp
be/src/runtime/plan_fragment_executor.cpp
be/src/vec/CMakeLists.txt
be/src/vec/columns/column.h
be/src/vec/columns/column_const.cpp
be/src/vec/columns/column_const.h
be/src/vec/columns/column_decimal.cpp
be/src/vec/columns/column_decimal.h
be/src/vec/columns/column_dummy.h
be/src/vec/columns/column_nullable.cpp
be/src/vec/columns/column_nullable.h
be/src/vec/columns/column_string.cpp
be/src/vec/columns/column_string.h
be/src/vec/columns/column_vector.cpp
be/src/vec/columns/column_vector.h
be/src/vec/common/pdqsort.h
be/src/vec/common/radix_sort.h
be/src/vec/core/sort_block.cpp
be/src/vec/core/sort_block.h
be/src/vec/core/sort_cursor.h
be/src/vec/core/sort_description.h
be/src/vec/data_types/data_type_nullable.cpp
be/src/vec/data_types/data_types_decimal.cpp
be/src/vec/exec/vexchange_node.cpp
be/src/vec/exec/vsort_exec_exprs.cpp
be/src/vec/exec/vsort_exec_exprs.h
be/src/vec/exec/vsort_node.cpp
be/src/vec/exec/vsort_node.h

1.enable the column permutation
2.support vsort node
Change-Id: I8d7cd59ed438f8b581632ffd6b2bdafd61ff7269
If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did …

[VSort Node] Support VSortNode

---

be/src/exec/data_sink.cpp
be/src/exec/data_sink.h
be/src/exec/exec_node.cpp
be/src/runtime/plan_fragment_executor.cpp
be/src/vec/CMakeLists.txt
be/src/vec/core/sort_cursor.h
be/src/vec/exec/vaggregation_node.cpp
be/src/vec/exec/vaggregation_node.h
be/src/vec/exec/vexchange_node.cpp
be/src/vec/exec/vexchange_node.h
be/src/vec/exec/volap_scan_node.cpp
be/src/vec/exec/volap_scan_node.h
be/src/vec/exec/volap_scanner.cpp
be/src/vec/exec/volap_scanner.h
be/src/vec/exec/vsort_node.cpp
be/src/vec/runtime/vdata_stream_recvr.h
fe/fe-core/src/main/java/org/apache/doris/common/profile/ProfileTreeBuilder.java
fe/fe-core/src/main/java/org/apache/doris/journal/bdbje/BDBEnvironment.java
fe/fe-core/src/main/java/org/apache/doris/planner/AggregationNode.java
fe/fe-core/src/main/java/org/apache/doris/planner/DataStreamSink.java
fe/fe-core/src/main/java/org/apache/doris/planner/ExchangeNode.java
fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java
fe/fe-core/src/main/java/org/apache/doris/planner/PlanNode.java
fe/fe-core/src/main/java/org/apache/doris/planner/ResultSink.java
fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java
fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java
gensrc/thrift/PlanNodes.thrift

1.Support vtop-n node
2.Fix the bug of profile of vec query
3.Refactoring the code the FE and BE, not need add new thrift type for vquery node
Change-Id: Icfbe5c5168047edf365ee483186ea96f78e40849
If this is a relatively large or complex change, kick …

[VTON-N Node] Support VTON-N Node

---

be/src/vec/core/block.cpp
be/src/vec/core/block.h
be/src/vec/exec/vaggregation_node.cpp
be/src/vec/exec/vaggregation_node.h
be/src/vec/sink/vdata_stream_sender.cpp
be/src/vec/sink/vdata_stream_sender.h

support multi-tablet group by agg

support multi-tablet group by agg

---

be/src/vec/CMakeLists.txt
be/src/vec/core/sort_cursor.h
be/src/vec/exec/vexchange_node.cpp
be/src/vec/exec/vexchange_node.h
be/src/vec/exec/vsort_node.cpp
be/src/vec/runtime/vdata_stream_recvr.cpp
be/src/vec/runtime/vdata_stream_recvr.h
be/src/vec/runtime/vsorted_run_merger.cpp
be/src/vec/runtime/vsorted_run_merger.h

Change-Id: I5f15771153fe8e982c78c581c42d5b1e25ab543f

[Sort] Support merge sort in ExchangeNode

---

be/src/exec/olap_scan_node.cpp
be/src/exec/olap_scan_node.h
be/src/exec/olap_scanner.cpp
be/src/vec/exec/vexchange_node.cpp
be/src/vec/exec/volap_scan_node.cpp
be/src/vec/exec/volap_scanner.cpp
be/src/vec/exec/volap_scanner.h
be/src/vec/exprs/vcast_expr.cpp
be/src/vec/runtime/vdata_stream_recvr.cpp
be/src/vec/runtime/vdata_stream_recvr.h
be/src/vec/runtime/vsorted_run_merger.cpp
be/src/vec/runtime/vsorted_run_merger.h

Change-Id: Ia7640db1556fc1255b8fe3e1134b8c8a80c72dd9

Add profile to analyze the performance

---

be/src/exec/olap_scan_node.cpp
be/src/exec/olap_scan_node.h
be/src/exec/olap_scanner.cpp
be/src/vec/CMakeLists.txt
be/src/vec/aggregate_functions/aggregate_function_null.h
be/src/vec/columns/column_nullable.h
be/src/vec/exec/volap_scanner.cpp
be/src/vec/functions/comparison_equels.cpp
be/src/vec/functions/comparison_greater.cpp
be/src/vec/functions/comparison_less.cpp

1. Speed up compilation 2. Optimization of sum nullable column

---

fe/fe-core/src/main/java/org/apache/doris/analysis/Expr.java
fe/fe-core/src/main/java/org/apache/doris/catalog/AggregateFunction.java
fe/fe-core/src/main/java/org/apache/doris/catalog/Function.java
fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java
fe/fe-core/src/main/java/org/apache/doris/common/FeMetaVersion.java
gensrc/thrift/Types.thrift

Support plan vectorized functiuon in FE

Support plan vectorized functiuon in FE

---

be/src/vec/aggregate_functions/aggregate_function_min_max.h
be/src/vec/core/block.cpp
be/src/vec/core/block.h
be/src/vec/data_types/data_type_nullable.cpp
be/src/vec/data_types/data_type_number_base.cpp
be/src/vec/functions/function.cpp

1. format
2. fix some -Wsign-compare -Wno-return

some warning fix

---

be/src/vec/CMakeLists.txt
be/src/vec/aggregate_functions/aggregate_function_simple_factory.h
be/src/vec/aggregate_functions/aggregate_function_uniq.cpp
be/src/vec/aggregate_functions/aggregate_function_uniq.h
be/src/vec/common/hash_table/hash_set.h
be/src/vec/common/hash_table/hash_table.h
be/src/vec/exec/vexchange_node.cpp

[1/2] support multi-distinct

---

fe/fe-core/src/main/java/org/apache/doris/analysis/ArithmeticExpr.java
fe/fe-core/src/main/java/org/apache/doris/analysis/BinaryPredicate.java
fe/fe-core/src/main/java/org/apache/doris/analysis/CastExpr.java
fe/fe-core/src/main/java/org/apache/doris/analysis/CompoundPredicate.java
fe/fe-core/src/main/java/org/apache/doris/catalog/Function.java
fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java

[Bug-Fix] Add function `addBuiltinBothScalaAndVectorized` to replace …`addBuiltin` to fix  the bug of expr analyze exception

---

be/src/vec/aggregate_functions/aggregate_function_count.cpp
be/src/vec/aggregate_functions/aggregate_function_count.h
be/src/vec/aggregate_functions/aggregate_function_null.cpp
be/src/vec/aggregate_functions/aggregate_function_simple_factory.h
be/src/vec/aggregate_functions/aggregate_function_uniq.cpp
be/src/vec/aggregate_functions/aggregate_function_uniq.h
be/src/vec/exec/vaggregation_node.cpp
be/src/vec/exec/vaggregation_node.h
be/src/vec/exprs/vectorized_agg_fn.cpp
fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java

support multi-distinct count 
eg:
```
select count(distinct k1), count(distinct k2) from baseall
```

[2/2] support multi-distinct count

---

be/src/vec/exec/vaggregation_node.cpp
be/src/vec/exec/vaggregation_node.h
be/src/vec/exprs/vectorized_agg_fn.cpp
be/src/vec/exprs/vectorized_agg_fn.h

support profile in agg node
build time
exec time
merge time
```
VAGGREGATION_NODE (id=1):(Active: 29.605ms, % non-child: 35.58%)
- BuildTime: 8.508ms
- ExecTime: 1.805ms
- MergeTime: 0ns
- PeakMemoryUsage: 4.00 KB
- RowsReturned: 0
- RowsReturnedRate: 0
```

add profile in agg node

---

be/src/exec/data_sink.cpp
be/src/runtime/mysql_result_writer.cpp
be/src/runtime/mysql_result_writer.h
be/src/runtime/result_sink.cpp
be/src/runtime/result_sink.h
be/src/runtime/result_writer.h
be/src/vec/exprs/vectorized_agg_fn.cpp
be/src/vec/exprs/vectorized_agg_fn.h
be/src/vec/sink/mysql_result_writer.cpp
be/src/vec/sink/result_writer.h
fe/fe-core/src/main/java/org/apache/doris/catalog/Function.java
fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java

Support agg functiuon for const vliteral

---

be/src/exprs/hll_function.cpp
be/src/exprs/hll_function.h
be/src/vec/CMakeLists.txt
be/src/vec/data_types/data_type_factory.hpp
be/src/vec/functions/abs.cpp
be/src/vec/functions/function_cast.h
be/src/vec/functions/function_const.h
be/src/vec/functions/function_string_or_array_to_t.h
be/src/vec/functions/function_string_to_string.h
be/src/vec/functions/hll_cardinality.cpp
be/src/vec/functions/hll_empty.cpp
be/src/vec/functions/hll_hash.cpp
be/src/vec/functions/simple_function_factory.h
fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java
gensrc/script/doris_builtins_functions.py
gensrc/script/gen_builtins_functions.py

Support hll function: hll_empty(), hll_hash(), hll_cardinality()

---

be/src/vec/CMakeLists.txt
be/src/vec/aggregate_functions/aggregate_function_distinct.cpp
be/src/vec/aggregate_functions/aggregate_function_distinct.h
be/src/vec/aggregate_functions/aggregate_function_simple_factory.h
be/src/vec/aggregate_functions/helpers.h
be/src/vec/aggregate_functions/key_holder_helpers.h
be/src/vec/common/hash_table/hash_set.h
be/src/vec/io/io_helper.h

```
select sum(distinct k1),max(distinct k2),min(distinct k3),min(distinct k4) from baseall;
```

support multi distinct sum/min/max

---

be/src/vec/data_types/data_type_date_time.h
be/test/vec/core/block_test.cpp

remove time zone from data_time

remove time zone from data_time

---

be/src/vec/CMakeLists.txt
be/src/vec/aggregate_functions/aggregate_function_hll_union_agg.cpp
be/src/vec/aggregate_functions/aggregate_function_hll_union_agg.h
be/src/vec/aggregate_functions/aggregate_function_simple_factory.h
be/src/vec/exec/volap_scanner.cpp
be/src/vec/functions/function_cast.h
fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java

1. support value cast to varchar 2.support hll_union_raw(), hll_union(), hll_union_agg()

---

fe/fe-core/src/main/java/org/apache/doris/analysis/Expr.java
fe/fe-core/src/main/java/org/apache/doris/analysis/InlineViewRef.java
fe/fe-core/src/main/java/org/apache/doris/analysis/LiteralExpr.java
fe/fe-core/src/main/java/org/apache/doris/analysis/SlotDescriptor.java
fe/fe-core/src/main/java/org/apache/doris/analysis/SlotRef.java

[Bug] Fix the bug of group by column is null

---

be/src/vec/exec/vaggregation_node.cpp

Support having clause

---

be/src/vec/CMakeLists.txt
be/src/vec/columns/column_complex.cpp
be/src/vec/columns/column_complex.h
be/src/vec/core/types.h
be/src/vec/data_types/data_type_bitmap.cpp
be/src/vec/data_types/data_type_bitmap.h
be/test/vec/core/CMakeLists.txt
be/test/vec/core/column_complex_test.cpp

define column bitmap

---

be/src/vec/exprs/vectorized_fn_call.cpp
be/src/vec/functions/function.cpp
be/src/vec/functions/function.h
be/src/vec/functions/function_binary_arithmetic.h
be/src/vec/functions/function_cast.h
be/src/vec/functions/function_const.h
be/src/vec/functions/function_string_or_array_to_t.h
be/src/vec/functions/function_string_to_string.h
be/src/vec/functions/function_unary_arithmetic.h
be/src/vec/functions/functions_comparison.h
be/src/vec/functions/functions_logical.cpp
be/src/vec/functions/functions_logical.h

modify IFunction Interface
void execute() -> Status execute

provide status return type

---

be/src/vec/columns/column.h
be/src/vec/columns/column_nullable.h
be/src/vec/core/block.cpp
be/src/vec/core/block.h
be/src/vec/core/column_with_type_and_name.cpp
be/src/vec/functions/functions_comparison.h
be/src/vec/sink/mysql_result_writer.cpp

fix nullable decimal column will core when comparison with other values

---

be/src/vec/common/hash_table/hash_table.h
be/src/vec/exec/vaggregation_node.cpp
be/src/vec/exec/vaggregation_node.h

Support Stream Pre Agg

---

be/src/runtime/types.h
be/src/vec/CMakeLists.txt
be/src/vec/columns/column_complex.h
be/src/vec/core/block.cpp
be/src/vec/core/types.h
be/src/vec/data_types/data_type_bitmap.cpp
be/src/vec/data_types/data_type_bitmap.h
be/src/vec/exec/volap_scanner.cpp
be/src/vec/functions/function.cpp
be/src/vec/functions/function.h
be/src/vec/functions/function_bitmap.cpp
be/src/vec/functions/function_bitmap.h
be/src/vec/functions/function_totype.h
be/src/vec/functions/simple_function_factory.h
be/src/vec/sink/mysql_result_writer.cpp
gensrc/script/doris_builtins_functions.py

```
select to_bitmap(k1) from baseall;
```

support to_bitmap

---

be/src/vec/data_types/data_type_bitmap.h
be/src/vec/functions/function_bitmap.cpp
be/src/vec/functions/function_totype.h
be/src/vec/sink/result_sink.cpp
gensrc/script/doris_builtins_functions.py

```
select bitmap_and(v1,v2) from bitmap_tb;
```

add binary bitmap function

---

be/src/vec/CMakeLists.txt
be/src/vec/core/block.cpp
be/src/vec/exec/vaggregation_node.cpp
be/src/vec/functions/is_not_null.cpp
be/src/vec/functions/is_null.cpp
be/src/vec/functions/simple_function_factory.h
fe/fe-core/src/main/java/org/apache/doris/analysis/IsNullPredicate.java
fe/fe-core/src/main/java/org/apache/doris/catalog/ScalarFunction.java

支持sql如下
```select xxx from table where col is null```
```select xxx from table where col is not null```
```select col is null from table ```
```select col is not null from table```
col可以是nullable也可以是非null的

[Function]Add is null / is not null

---

be/src/runtime/datetime_value.h
be/src/vec/CMakeLists.txt
be/src/vec/functions/date_time_transforms.h
be/src/vec/functions/function_date_or_datetime_to_something.h
be/src/vec/functions/function_string_to_string.h
be/src/vec/functions/hll_hash.cpp
be/src/vec/functions/simple_function_factory.h
be/src/vec/functions/time_of_function.cpp
be/src/vec/functions/to_time_function.cpp
gensrc/script/doris_builtins_functions.py

Support day, hour, minute, month, year, second, weekofyear, dayofmonth, dayofyear, dayofweek function.

---

be/src/exprs/hybrid_set.h
be/src/vec/CMakeLists.txt
be/src/vec/columns/column_set.h
be/src/vec/exec/vsort_node.cpp
be/src/vec/exprs/vexpr.cpp
be/src/vec/exprs/vin_predicate.cpp
be/src/vec/exprs/vin_predicate.h
be/src/vec/exprs/vliteral.cpp
be/src/vec/functions/in.cpp
be/src/vec/functions/simple_function_factory.h

Support in/not in predicate

---

be/src/vec/functions/function_string.cpp
be/src/vec/functions/function_string.h
be/src/vec/functions/function_totype.h
be/src/vec/functions/simple_function_factory.h
be/src/vec/utils/util.hpp
gensrc/script/doris_builtins_functions.py

```
substring/concat/concat_ws
asii/find_in_set/space
append_trailing_char_if_absent
```
fix some const column problem

support some string function

---

be/src/exprs/timestamp_functions.cpp
be/src/exprs/timestamp_functions.h
be/src/runtime/datetime_value.cpp
be/src/runtime/datetime_value.h
be/src/vec/CMakeLists.txt
be/src/vec/functions/date_time_transforms.h
be/src/vec/functions/function_date_or_datetime_computation.cpp
be/src/vec/functions/function_date_or_datetime_computation.h
be/src/vec/functions/function_date_or_datetime_to_string.cpp
be/src/vec/functions/function_date_or_datetime_to_string.h
be/src/vec/functions/function_datetime_string_to_string.cpp
be/src/vec/functions/function_datetime_string_to_string.h
be/src/vec/functions/simple_function_factory.h
be/src/vec/functions/to_time_function.cpp
build.sh
fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java
gensrc/script/doris_builtins_functions.py
gensrc/script/gen_builtins_functions.py

support unix_timestamp,   from_unixtime,utc_timestamp,from_days,date_format,to_date,date,dayname,monthname

Support Time Function

---

be/src/vec/aggregate_functions/aggregate_function_null.h
be/src/vec/exec/vaggregation_node.cpp
be/src/vec/exec/volap_scanner.cpp
be/src/vec/exprs/vectorized_agg_fn.cpp
fe/fe-core/src/main/java/org/apache/doris/analysis/Expr.java
fe/fe-core/src/main/java/org/apache/doris/catalog/Function.java
fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java
fe/fe-core/src/main/java/org/apache/doris/catalog/ScalarFunction.java

[Bug] Fix bug, support nullable function, and optimal

---

be/src/vec/CMakeLists.txt
be/src/vec/functions/function_json.cpp
be/src/vec/functions/simple_function_factory.h
gensrc/script/doris_builtins_functions.py

```
get_json_int
get_json_double
get_json_string
```

[vec] support json functions

---

be/CMakeLists.txt
be/src/exec/olap_scan_node.cpp
be/src/gutil/endian.h
be/src/vec/core/block.h
be/src/vec/exec/volap_scanner.cpp
be/src/vec/functions/function_cast.h
be/src/vec/functions/function_unary_arithmetic.h
fe/fe-core/src/main/java/org/apache/doris/analysis/ArithmeticExpr.java
fe/fe-core/src/main/java/org/apache/doris/analysis/IsNullPredicate.java
fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java
fe/fe-core/src/main/java/org/apache/doris/catalog/ScalarFunction.java

2. Remove idle cast in math compute of vectorized execute engine
3. Remove some virtual function call in _convert_to_block functinon in OlapScanner
If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by …

1. Change compile flag to enable function vectorized

---

be/src/vec/CMakeLists.txt
be/src/vec/functions/if.cpp
be/src/vec/functions/ifnull.cpp
be/src/vec/functions/is_not_null.cpp
be/src/vec/functions/nullif.cpp
be/src/vec/functions/simple_function_factory.h

support ifnull/nullif function

support ifnull/nullif

---

be/src/vec/exec/vaggregation_node.cpp
fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java

1. Remove the unless cast 2. Add some profile in vaggregation_node

---

be/src/vec/functions/function_const.h
be/src/vec/functions/function_math_binary_float64.h
be/src/vec/functions/math.cpp
gensrc/script/doris_builtins_functions.py
gensrc/script/gen_builtins_functions.py

Fix math function error

---

be/CMakeLists.txt
be/src/util/binary_cast.hpp
be/src/vec/aggregate_functions/aggregate_function.h
be/src/vec/aggregate_functions/aggregate_function_sum.cpp
be/src/vec/aggregate_functions/factory_helpers.h
be/src/vec/common/allocator.h
be/src/vec/common/assert_cast.h
be/src/vec/data_types/data_type.cpp
be/src/vec/data_types/data_type_date.cpp
be/src/vec/data_types/data_type_date_time.cpp
be/src/vec/exec/vaggregation_node.cpp
be/src/vec/exec/vaggregation_node.h
be/src/vec/exprs/vectorized_agg_fn.cpp
be/src/vec/exprs/vectorized_agg_fn.h
be/src/vec/functions/date_time_transforms.h
be/src/vec/functions/function_cast.h
be/src/vec/functions/function_date_or_datetime_computation.h
be/src/vec/functions/math.cpp
be/src/vec/io/io_helper.h
be/src/vec/sink/result_sink.cpp

fix strict-warning, add some profile, use status instead of exception

---

be/src/exec/exec_node.cpp
be/src/exec/exec_node.h
be/src/runtime/datetime_value.h
be/src/runtime/descriptors.cpp
be/src/runtime/descriptors.h
be/src/vec/CMakeLists.txt
be/src/vec/exec/vblocking_join_node.cpp
be/src/vec/exec/vblocking_join_node.h
be/src/vec/exec/vcross_join_node.cpp
be/src/vec/exec/vcross_join_node.h
be/src/vec/functions/function_cast.h
be/src/vec/io/io_helper.h

support cross join node and fix some bug

---

be/src/runtime/data_stream_recvr.cc
be/src/vec/core/block.cpp
be/src/vec/core/block.h
be/src/vec/data_types/data_type.h
be/src/vec/data_types/data_type_bitmap.cpp
be/src/vec/data_types/data_type_bitmap.h
be/src/vec/data_types/data_type_decimal.cpp
be/src/vec/data_types/data_type_decimal.h
be/src/vec/data_types/data_type_nothing.cpp
be/src/vec/data_types/data_type_nothing.h
be/src/vec/data_types/data_type_nullable.cpp
be/src/vec/data_types/data_type_nullable.h
be/src/vec/data_types/data_type_number_base.cpp
be/src/vec/data_types/data_type_number_base.h
be/src/vec/data_types/data_type_string.cpp
be/src/vec/data_types/data_type_string.h
be/src/vec/exec/vexchange_node.cpp
be/src/vec/exec/vexchange_node.h
be/src/vec/exec/vsort_node.cpp
be/src/vec/io/io_helper.h
be/src/vec/runtime/vdata_stream_recvr.cpp
be/src/vec/sink/vdata_stream_sender.cpp
gensrc/proto/data.proto

Add The Profile For VExec

---

be/src/vec/columns/column.h
be/src/vec/columns/column_vector.cpp
be/src/vec/data_types/data_type_bitmap.cpp
be/src/vec/data_types/data_type_decimal.cpp
be/src/vec/data_types/data_type_nullable.cpp
be/src/vec/data_types/data_type_number_base.cpp
be/src/vec/data_types/data_type_string.cpp
be/src/vec/io/io_helper.h

refactor the code of serialize/deserialize

---

be/src/exec/cross_join_node.cpp
be/src/vec/aggregate_functions/aggregate_function_count.h
be/src/vec/aggregate_functions/aggregate_function_distinct.cpp
be/src/vec/aggregate_functions/aggregate_function_distinct.h
be/src/vec/aggregate_functions/aggregate_function_simple_factory.h
be/src/vec/core/block.cpp
be/src/vec/core/sort_block.cpp
be/src/vec/core/sort_cursor.h
be/src/vec/data_types/data_type.h
be/src/vec/data_types/data_type_nullable.cpp
be/src/vec/exec/vblocking_join_node.cpp
be/src/vec/exec/vblocking_join_node.h
be/src/vec/exec/vcross_join_node.cpp
be/src/vec/exec/vcross_join_node.h
be/src/vec/exec/volap_scan_node.cpp
be/src/vec/exec/vsort_node.cpp
be/src/vec/exec/vsort_node.h
be/src/vec/runtime/vdata_stream_recvr.cpp

2. Opt the mem usage of TOPN node
3. Some bug fixed

1. Add MemTracker In Sort/Scan/Exchange/Corss Join Node

---

be/src/vec/exec/vcross_join_node.cpp
be/src/vec/exec/vcross_join_node.h
be/src/vec/exec/vsort_node.cpp
be/src/vec/exec/vsort_node.h

Fix the mem leak and mem limit

---

be/src/exec/olap_scan_node.cpp
be/src/exec/olap_scanner.cpp
be/src/vec/exec/volap_scanner.cpp
fe/fe-core/src/main/java/org/apache/doris/analysis/ArithmeticExpr.java
fe/fe-core/src/main/java/org/apache/doris/analysis/IsNullPredicate.java
fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java
fe/fe-core/src/main/java/org/apache/doris/catalog/ScalarFunction.java

1. Remove useless cast in math compute

---

fe/fe-core/src/main/java/org/apache/doris/analysis/CastExpr.java
fe/fe-core/src/main/java/org/apache/doris/analysis/Expr.java
fe/fe-core/src/main/java/org/apache/doris/analysis/FunctionCallExpr.java
fe/fe-core/src/main/java/org/apache/doris/catalog/AggregateFunction.java
fe/fe-core/src/main/java/org/apache/doris/catalog/Function.java
fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java
fe/fe-core/src/main/java/org/apache/doris/catalog/ScalarFunction.java
fe/fe-core/src/test/java/org/apache/doris/catalog/FunctionSetTest.java
fe/fe-core/src/test/java/org/apache/doris/planner/StreamLoadScanNodeTest.java

2. Add Nullable mode in AggregateFunction

1. Refactored constructor of Function/ScalaFunction/AggregateFunction

---

be/src/vec/aggregate_functions/aggregate_function.h
be/src/vec/aggregate_functions/aggregate_function_avg.h
be/src/vec/aggregate_functions/aggregate_function_bitmap.h
be/src/vec/aggregate_functions/aggregate_function_count.h
be/src/vec/aggregate_functions/aggregate_function_distinct.h
be/src/vec/aggregate_functions/aggregate_function_hll_union_agg.h
be/src/vec/aggregate_functions/aggregate_function_min_max.h
be/src/vec/aggregate_functions/aggregate_function_nothing.h
be/src/vec/aggregate_functions/aggregate_function_null.h
be/src/vec/aggregate_functions/aggregate_function_sum.h
be/src/vec/aggregate_functions/aggregate_function_uniq.h
be/src/vec/common/hash_table/hash_table.h
be/src/vec/common/string_buffer.hpp
be/src/vec/core/field.cpp
be/src/vec/data_types/data_type_bitmap.cpp
be/src/vec/data_types/data_type_bitmap.h
be/src/vec/exec/vaggregation_node.cpp
be/src/vec/exec/vsort_node.cpp
be/src/vec/functions/function_cast.h
be/src/vec/io/io_helper.h
be/src/vec/io/var_int.h

Refactor the seriable/deseriable of agg

---

be/src/exec/partitioned_aggregation_node.cc
be/src/exprs/aggregate_functions.cpp
be/src/exprs/aggregate_functions.h
be/src/exprs/anyval_util.h
be/src/exprs/expr_value.h
be/src/exprs/new_agg_fn_evaluator.cc
be/src/runtime/type_limit.h
be/src/vec/aggregate_functions/aggregate_function_null.cpp
be/src/vec/aggregate_functions/aggregate_function_simple_factory.h
be/src/vec/exec/vaggregation_node.cpp
be/src/vec/exprs/vectorized_agg_fn.cpp
be/src/vec/exprs/vectorized_agg_fn.h
fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java
fe/fe-core/src/main/java/org/apache/doris/qe/StmtExecutor.java

1. Fix the bug of muli distinct function register
2. Rewrite the init function of min/max aggregatetion
3. Fix the bug of distinct function mixed normal aggregatetion function
If this is a relatively large or complex change, kick off the discussion at …

Refactor code of aggregate Node

---

fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java

fix compile problem

---

fe/fe-core/src/main/java/org/apache/doris/analysis/DateLiteral.java
fe/fe-core/src/test/java/org/apache/doris/analysis/CaseExprTest.java
fe/fe-core/src/test/java/org/apache/doris/planner/PlannerTest.java
gensrc/script/doris_builtins_functions.py

change bitmap_count to DEPEND_ON_ARGUMENT

Remove unused datetime check

---

be/src/runtime/primitive_type.h
be/src/vec/common/aggregation_common.h
be/src/vec/common/columns_hashing.h
be/src/vec/common/columns_hashing_impl.h
be/src/vec/common/hash_table/hash_table.h
be/src/vec/exec/join/join_op.h
be/src/vec/exec/join/vacquire_list.hpp
be/src/vec/exec/join/vhash_join_node.cpp
be/src/vec/exec/join/vhash_join_node.h

support nullable column join and eq_for_null join
```
select count(*) from baseall_x t1 join baseall_x t2 on t1.k3 = t2.k3;
```
```
select count(*) from baseall_x t1 join baseall_x t2 on t1.k3 <=> t2.k3;
```

[vec-join] support nullable column join and eq_for_null join

---

be/src/vec/core/block.h
be/src/vec/runtime/vdata_stream_recvr.cpp
be/src/vec/runtime/vdata_stream_recvr.h
be/src/vec/sink/result_sink.cpp
be/src/vec/sink/vdata_stream_sender.cpp
be/src/vec/sink/vdata_stream_sender.h

1. DCEHECK failed in MemTracker
2. Del use move param to mem reuse
3. Support LocalBytesSent Count
If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and …

[Local Exchange] Fix the bug:

---

be/src/runtime/plan_fragment_executor.cpp
be/src/vec/columns/column.h
be/src/vec/columns/column_complex.h
be/src/vec/columns/column_const.h
be/src/vec/columns/column_decimal.h
be/src/vec/columns/column_nullable.h
be/src/vec/columns/column_string.cpp
be/src/vec/columns/column_string.h
be/src/vec/columns/column_vector.h
be/src/vec/common/allocator.h
be/src/vec/common/hash_table/hash_table.h
be/src/vec/core/block.cpp
be/src/vec/core/block.h
be/src/vec/exec/vaggregation_node.cpp
be/src/vec/exec/vaggregation_node.h
be/src/vec/exec/vblocking_join_node.cpp
be/src/vec/exec/vblocking_join_node.h
be/src/vec/exec/vcross_join_node.cpp
be/src/vec/exec/volap_scan_node.cpp
be/src/vec/exec/volap_scan_node.h
be/src/vec/exec/volap_scanner.cpp
be/src/vec/exec/vsort_node.cpp
be/src/vec/exec/vunion_node.cpp
be/src/vec/runtime/vsorted_run_merger.cpp
be/src/vec/sink/vdata_stream_sender.cpp

Support Block Mem Reuse of Block mem 

[MemReuse] Support MemReuse in Vec Exec Engine

---

be/src/vec/aggregate_functions/aggregate_function_distinct.cpp
be/src/vec/aggregate_functions/aggregate_function_null.cpp
be/src/vec/aggregate_functions/aggregate_function_uniq.cpp
be/src/vec/aggregate_functions/aggregate_function_uniq.h
be/src/vec/core/sort_cursor.h
be/src/vec/runtime/vdata_stream_recvr.cpp
be/src/vec/runtime/vsorted_run_merger.cpp

1. Core in memtracker release
2. Core in merge sort in Exchange Node
3. Support Muil Distinct of Decimal Type
If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you …

[Bug] Fix the 3 bug following

---

be/src/vec/olap/vcollect_iterator.cpp
be/src/vec/olap/vcollect_iterator.h

[Vec Storage Engine] Add VCollectIterator Interface

---

be/src/olap/row_block2.cpp
be/src/olap/row_block2.h
be/src/olap/rowset/alpha_rowset_reader.h
be/src/olap/rowset/beta_rowset_reader.cpp
be/src/olap/rowset/beta_rowset_reader.h
be/src/olap/rowset/rowset_reader.h
be/src/vec/core/block.cpp
be/src/vec/core/block.h

[Reader-Vec] Support RowBlockV2 Convert To Vec Block

---

be/src/runtime/types.h
be/src/vec/columns/column.h
be/src/vec/common/cow.h
be/src/vec/core/block.h
be/src/vec/data_types/data_type_factory.hpp
be/src/vec/data_types/number_traits.h
be/src/vec/exec/vcross_join_node.cpp
be/src/vec/exec/volap_scanner.cpp
be/src/vec/exec/vunion_node.cpp
be/src/vec/functions/function.cpp
fe/fe-core/src/main/java/org/apache/doris/analysis/ArithmeticExpr.java
fe/fe-core/src/main/java/org/apache/doris/catalog/Type.java

1. Fix cast failed in nullable column
2. Fix arithmetic expr core bug
3. Fix core of abs(bigint)
4. Fix union node get wrong type result to wrong answer
5. Fix core bug in math compute in Vec Engine
6. Fix bug of core in union node because of type is wrong
7. Fix bug of mem reuse
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look …

[Bug fix] The bug following be fixed:

---

be/src/olap/rowset/segment_v2/page_decoder.h
be/src/olap/rowset/segment_v2/rle_page.h

Vectorized read implementation for RLE decode.

---

be/src/olap/generic_iterators.cpp
be/src/olap/generic_iterators.h
be/src/olap/iterators.h
be/src/olap/rowset/beta_rowset_reader.cpp
be/src/olap/rowset/beta_rowset_reader.h
be/src/olap/rowset/rowset_reader.h
be/src/olap/rowset/segment_v2/empty_segment_iterator.cpp
be/src/olap/rowset/segment_v2/empty_segment_iterator.h
be/src/olap/rowset/segment_v2/segment_iterator.cpp
be/src/olap/rowset/segment_v2/segment_iterator.h
be/src/olap/schema.h
be/src/vec/CMakeLists.txt
be/src/vec/olap/vgeneric_iterators.cpp
be/src/vec/olap/vgeneric_iterators.h

MergeIterator support vectorized next_batch interface

---

be/src/vec/functions/function_string.cpp

select ascii('北京,love');
[diff data:][{'palo_data': -27L, 'mysql_data': 229L}]
afer fix:

[bug]fix ascii function

---

be/src/vec/functions/function_string.h

[Bug]fix the concat_ws function return type nullable or not nullable

---

be/src/vec/olap/vgeneric_iterators.cpp

bugfix: vgeneric_iterators debug mode compile error

---

be/src/vec/functions/function_string.h

sql case:
SELECT LPAD('hi',1,'123')
SELECT RPAD('hi',1,'123')
wrong answer:
hi
hi
expect answer:
h
h

[Bug]fix pad wrong answer

---

be/src/vec/functions/function_date_or_datetime_computation.h

[bug]make some timeadd operations nullable

---

be/src/vec/aggregate_functions/aggregate_function_min_max.cpp
be/src/vec/aggregate_functions/aggregate_function_min_max.h
be/src/vec/data_types/data_type_date.cpp
be/src/vec/data_types/data_type_date_time.cpp
be/src/vec/data_types/number_traits.h
be/src/vec/exec/join/vhash_join_node.cpp
be/src/vec/functions/function.h
be/src/vec/functions/function_cast.cpp
be/src/vec/functions/function_date_or_datetime_computation.h
be/src/vec/functions/if.cpp
be/src/vec/functions/math.cpp
fe/fe-core/src/main/java/org/apache/doris/analysis/ArithmeticExpr.java
gensrc/script/doris_builtins_functions.py

1. support mod in vec
2. fix bug of return type mod
3. support decimal min/max
4. fix bug of datetime cast
5. fix bug of log wrong result
6. hash join support conjunct filter
If this is a relatively large or complex change, kick off the discussion at …

[Bug] Some bug fix and feature support

---

be/test/vec/function/CMakeLists.txt
be/test/vec/function/function_string_test.cpp
gensrc/script/doris_builtins_functions.py

functions have done: upper, lower, substr, strright, strleft.

some string functions unit test

---

be/src/util/url_coding.cpp
be/src/vec/functions/function_string.cpp
be/src/vec/functions/function_totype.h
be/test/vec/aggregate_functions/agg_test.cpp
be/test/vec/exec/CMakeLists.txt
be/test/vec/function/function_string_test.cpp
gensrc/script/doris_builtins_functions.py

[vec] support base64 function

---

be/src/vec/functions/function_string.cpp
be/test/vec/function/function_string_test.cpp

fix-reverse and add UT

---

be/test/vec/function/function_string_test.cpp

[UT]add instr/concat/concat_ws ut

---

be/src/olap/schema.cpp
be/src/olap/schema.h
be/src/vec/olap/vgeneric_iterators.cpp
be/test/olap/generic_iterators_test.cpp
be/test/vec/exec/CMakeLists.txt
be/test/vec/exec/vgeneric_iterators_test.cpp

provide unit test for VMergeIterator

---

be/test/vec/function/function_string_test.cpp

Rewrite and add string UT according to the util template

---

be/src/vec/common/hash_table/fixed_hash_map.h
be/src/vec/common/hash_table/fixed_hash_table.h
be/src/vec/common/hash_table/hash_table.h
be/src/vec/exec/vaggregation_node.cpp
be/src/vec/exec/vaggregation_node.h

Introduce int fixed key(int8/int16/int32/in64)

Introduce int fixed key(int8/int16/int32/in64)

---

be/src/vec/columns/column_nullable.cpp
be/src/vec/sink/vdata_stream_sender.cpp

bucket shuffle hash partitioned with crc hash

[Feature]bucket shuffle hash partitioned with crc hash

---

be/src/vec/olap/vgeneric_iterators.cpp

no need rebuild Block，use clear_column_data is more fitable

vgeneric_iterators block_reset improvement

---

be/src/olap/rowset/segment_v2/column_reader.cpp
be/src/olap/rowset/segment_v2/column_reader.h

FileColumnIterator support vectorized next_batch interface.

FileColumnIterator support vectorized next_batch interface

---

be/src/vec/common/columns_hashing.h
be/src/vec/exec/join/vhash_join_node.cpp
be/src/vec/exec/vaggregation_node.cpp
be/src/vec/exec/vaggregation_node.h

[AGG] Introduce int fixed keys UINT64, UINT128,UInt256 in AggregateNode

---

be/src/exec/exec_node.cpp
be/src/exprs/math_functions.cpp
be/src/exprs/math_functions.h
be/src/vec/functions/math.cpp
be/test/vec/function/CMakeLists.txt
be/test/vec/function/function_math_test.cpp
be/test/vec/function/function_test_util.h
be/test/vec/function/function_time_test.cpp
gensrc/script/doris_builtins_functions.py

add datetime/math functions unit test;
and change sign function return type to int8;

[UT]datetime&&math functions unit test

---

be/src/olap/collect_iterator.cpp
be/src/olap/reader.cpp
be/src/olap/reader.h
be/src/olap/rowset/alpha_rowset_reader.h
be/src/olap/rowset/beta_rowset_reader.h
be/src/olap/rowset/rowset_reader.h
be/src/vec/core/block.cpp
be/src/vec/core/block.h
be/src/vec/olap/vcollect_iterator.cpp
be/src/vec/olap/vcollect_iterator.h

support vectorized collect_iterator

support vectorized collect_iterator

---

be/src/olap/rowset/segment_v2/binary_dict_page.cpp
be/src/olap/rowset/segment_v2/binary_dict_page.h
be/src/olap/rowset/segment_v2/binary_plain_page.h
be/src/olap/rowset/segment_v2/binary_prefix_page.h
be/src/olap/rowset/segment_v2/bitshuffle_page.h
be/src/olap/rowset/segment_v2/frame_of_reference_page.h
be/src/olap/rowset/segment_v2/plain_page.h

same to #131 ,just rebase the lastest master and open a new pr

support string/binary/int decoder

---

be/src/vec/common/hash_table/hash.h
be/src/vec/common/uint128.h
be/src/vec/exec/join/join_op.h
be/src/vec/exec/join/vhash_join_node.cpp
be/src/vec/exec/join/vhash_join_node.h
be/src/vec/exec/vaggregation_node.h
fe/fe-core/src/main/java/org/apache/doris/analysis/BinaryPredicate.java
fe/fe-core/src/main/java/org/apache/doris/planner/HashJoinNode.java

[vec-join] Opt Fixed keys in hash join and support left/right/full join
1. support left/right/full join
2. join opt of fixed keys
3. support build join column nullable and probe join column nullable

[vec-join] Opt Fixed keys in hash join and support left/right/full join

---

be/src/vec/core/block.cpp
be/src/vec/exec/vcross_join_node.cpp
be/src/vec/exec/vcross_join_node.h

[Cross Join] Refactored the code of cross join to improve performance.

---

be/src/vec/functions/math.cpp
be/test/vec/function/function_math_test.cpp

round function: int round(double) && double round(double, int)

[Function] add round function

---

be/src/runtime/types.h

[Bug] Support STRING type field on vectorized engine

---

be/src/vec/common/columns_hashing.h
be/src/vec/core/block.cpp
be/src/vec/core/block.h
be/src/vec/exec/join/join_op.h
be/src/vec/exec/join/vacquire_list.hpp
be/src/vec/exec/join/vhash_join_node.cpp
be/src/vec/exec/join/vhash_join_node.h
be/src/vec/exec/vaggregation_node.cpp
be/src/vec/exec/vsort_node.cpp
be/src/vec/functions/in.cpp
fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
fe/fe-core/src/main/java/org/apache/doris/analysis/SelectStmt.java
fe/fe-core/src/main/java/org/apache/doris/analysis/TableRef.java
fe/fe-core/src/main/java/org/apache/doris/planner/HashJoinNode.java
fe/fe-core/src/main/java/org/apache/doris/planner/PlanNode.java
gensrc/script/doris_builtins_functions.py
gensrc/thrift/PlanNodes.thrift

[Join] Refactored the code of join and support left/right semi anti join and other join conjunt

---

be/src/vec/functions/math.cpp

@Gabriel39.  I simplify your function bin code by using template class FunctionUnaryToTyp.

[code refactor] Simplify function bin impl

---

be/src/util/runtime_profile.h
be/src/vec/common/hash_table/hash_table.h
be/src/vec/exec/join/vacquire_list.hpp
be/src/vec/exec/join/vhash_join_node.cpp
be/src/vec/exec/join/vhash_join_node.h

[Feature] vhash join profile collect

---

be/src/exec/exec_node.cpp
be/src/vec/CMakeLists.txt
be/src/vec/common/hash_table/hash_table.h
be/src/vec/exec/join/join_op.h
be/src/vec/exec/vexcept_node.cpp
be/src/vec/exec/vexcept_node.h
be/src/vec/exec/vintersect_node.cpp
be/src/vec/exec/vintersect_node.h
be/src/vec/exec/vset_operation_node.cpp
be/src/vec/exec/vset_operation_node.h
be/src/vec/exec/vunion_node.cpp
be/src/vec/exec/vunion_node.h

[Feature]Add VIntersect/VExcept node

---

be/src/vec/exec/vexcept_node.h
be/src/vec/exec/vset_operation_node.h

fix operation node about output

[Bug]fix operation node about output

---

be/src/vec/aggregate_functions/aggregate_function_sum.cpp
be/src/vec/aggregate_functions/aggregate_function_sum.h

[Refactor] remove kahan sum

---

be/src/exec/es/es_scroll_parser.cpp
be/src/exec/es/es_scroll_parser.h
be/src/exec/es_http_scan_node.cpp
be/src/exec/es_http_scan_node.h
be/src/exec/es_http_scanner.h
be/src/exec/exec_node.cpp
be/src/vec/CMakeLists.txt
be/src/vec/exec/ves_http_scan_node.cpp
be/src/vec/exec/ves_http_scan_node.h
be/src/vec/exec/ves_http_scanner.cpp
be/src/vec/exec/ves_http_scanner.h

Support ES scan on vectorized engine

[Feature][Vectorized] Support ES scan on vectorized engine

---

be/src/vec/functions/like.cpp

This PR fixed linking error when build in release mode, which was introduced in #182 .

[Bug] Fix linking error when build in release mode.

---

be/src/vec/exec/join/vhash_join_node.cpp
be/src/vec/exec/vaggregation_node.cpp
be/src/vec/exec/vcross_join_node.cpp
be/src/vec/exec/ves_http_scan_node.cpp
be/src/vec/exec/volap_scanner.cpp
be/src/vec/exprs/vexpr_context.cpp
be/src/vec/exprs/vexpr_context.h
be/src/vec/functions/like.cpp

[Bug] fix empty block core

---

be/src/vec/common/allocator.h
be/src/vec/core/accurate_comparison.h
be/src/vec/core/decimal_comparison.h
be/src/vec/exec/vblocking_join_node.cpp
be/src/vec/exprs/vcast_expr.cpp
be/src/vec/exprs/vectorized_fn_call.cpp
be/src/vec/exprs/vexpr.cpp
be/src/vec/exprs/vexpr.h
be/src/vec/exprs/vin_predicate.cpp
be/src/vec/functions/functions_comparison.h
be/src/vec/functions/like.cpp

1. Refactored the logic of DateTime comparison size, and does not depend on the endianness of the type. Need to be compatible with the logic of the old version of doris, but it will cause the performance of DateTime comparison to decrease
2. Delete the useless code logic in the comparison function, and modify the format
3. Fixed the core problem of in/cast in function context
If this is a relatively large or complex change, kick off the discussion …

[Function] Refactor code of datetime comparetion and delete some unless code

---

be/src/vec/functions/simple_function_factory.h

Remove noisy log.
Ping @zbtzbtzbt @HappenLee, please take a look.

Avoid noisy log `key_str` when register function.

---

be/src/vec/exec/vaggregation_node.cpp

[Agg] Fix stream pre agg no effect and add profile of stream pre agg

---

fe/fe-core/src/main/java/org/apache/doris/planner/SingleNodePlanner.java

[Bug] Skip wrap function of tuple_is_null in exec vec engine

---

be/src/vec/functions/function_math_binary_float64.h
be/src/vec/functions/function_math_unary.h
be/src/vec/functions/math.cpp
be/test/vec/function/function_math_test.cpp

使用新的函数重载注册逻辑SFINAE重写round函数，@zhangstar333 ，相关pr：
https://github.com/doris-vectorized/doris-vectorized/pull/201
https://github.com/doris-vectorized/doris-vectorized/pull/233 @HappenLee 
优点是:
1.可以继承一些类，如 `FunctionMathUnary`，减少代码量（虽然这里并没有减少代码，但这种实现是一种通用方法）
2.新版本的SFINAE可以避免之前用默认模板参数导致的模板膨胀的问题
If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what …

Refactor vec function round

---

be/src/vec/data_types/data_type.h
be/src/vec/functions/function.h
be/src/vec/functions/like.h
be/test/vec/function/function_like_test.cpp

Before this PR, BE would crash when running SQL `SELECT * FROM t WHERE  value like null` if we build BE in debug mode.

Fix null constant argument issue in like

---

be/src/vec/functions/function_string.cpp
be/src/vec/functions/function_string.h
be/src/vec/functions/function_totype.h
be/test/vec/function/function_string_test.cpp

- Make the framework automatically handle Null values automatically;
- Adjust the code format to clang-format;

[Function] Optimization parse_url, base64, unhex function

---

be/src/exec/olap_scan_node.cpp
be/src/exprs/runtime_filter.cpp
be/src/exprs/runtime_filter.h
be/src/exprs/runtime_filter_slots.h
be/src/util/runtime_profile.h
be/src/vec/common/hash_table/hash_map.h
be/src/vec/exec/join/join_op.h
be/src/vec/exec/join/vhash_join_node.cpp
be/src/vec/exec/join/vhash_join_node.h
be/src/vec/exec/volap_scan_node.cpp
be/src/vec/exec/volap_scan_node.h
be/src/vec/exprs/vexpr_context.cpp
be/src/vec/exprs/vexpr_context.h
be/src/vec/exprs/vin_predicate.cpp
fe/fe-core/src/main/java/org/apache/doris/planner/Planner.java

[Feature] support runtime filter

---

be/src/exprs/v_string_functions.h
be/src/vec/exec/volap_scan_node.cpp
be/src/vec/functions/function_string.cpp

Fix hex function bug

---

be/src/vec/CMakeLists.txt
be/src/vec/columns/column.h
be/src/vec/columns/column_complex.h
be/src/vec/columns/column_decimal.h
be/src/vec/columns/column_nullable.cpp
be/src/vec/columns/column_nullable.h
be/src/vec/columns/column_string.cpp
be/src/vec/columns/column_string.h
be/src/vec/columns/column_vector.h
be/src/vec/exprs/vcase_expr.cpp
be/src/vec/exprs/vcase_expr.h
be/src/vec/exprs/vexpr.cpp
be/src/vec/functions/function_case.cpp
be/src/vec/functions/function_case.h
be/src/vec/functions/simple_function_factory.h

[Feature] support case when

---

be/src/vec/exprs/vcase_expr.cpp
be/src/vec/functions/function_case.h

[Feature] case when support decimal

---

be/src/vec/exprs/vcompound_pred.h
be/src/vec/exprs/vectorized_fn_call.h
be/src/vec/exprs/vexpr.cpp
be/src/vec/exprs/vexpr_context.cpp
fe/fe-core/src/main/java/org/apache/doris/analysis/ArithmeticExpr.java

[Bug] fix support and/or/not compound pred & fix 'boolean & boolean' & fix is_clone removed

---

be/src/exec/olap_scan_node.h
be/src/olap/reader.h
be/src/olap/row_block2.cpp
be/src/olap/row_block2.h
be/src/olap/rowset/beta_rowset_reader.cpp
be/src/vec/CMakeLists.txt
be/src/vec/columns/column_nullable.h
be/src/vec/exec/volap_scan_node.cpp
be/src/vec/exec/volap_scan_node.h
be/src/vec/exec/volap_scanner.cpp
be/src/vec/exec/volap_scanner.h
be/src/vec/olap/block_reader.cpp
be/src/vec/olap/block_reader.h
be/src/vec/olap/vcollect_iterator.cpp
be/src/vec/olap/vcollect_iterator.h
fe/fe-core/src/main/java/org/apache/doris/planner/OlapScanNode.java

[Reader Vec] Reader vec in duplicate key

---

be/src/runtime/primitive_type.h

when column type is string, we should consider it variable type

---

be/src/olap/rowset/beta_rowset_reader.cpp
be/src/runtime/mysql_result_writer.cpp
be/src/runtime/primitive_type.h
be/src/vec/exec/volap_scan_node.cpp
be/src/vec/exec/volap_scanner.cpp
be/src/vec/exec/volap_scanner.h
be/src/vec/functions/function_string.h
be/src/vec/sink/mysql_result_writer.cpp
be/src/vec/sink/mysql_result_writer.h

[Feature] refactor result_writer && fix convert_tuple_timer count

---

be/src/exec/exec_node.cpp
be/src/vec/CMakeLists.txt
be/src/vec/exec/vempty_set_node.cpp
be/src/vec/exec/vempty_set_node.h

run select tc1 from t3 where tc2='2020-10-34 20:06:20'; throw exception:vempty_set_node not implemented.
- [x ] New feature (non-breaking change which adds functionality)

support vempty_set_node

---

be/src/vec/exec/join/vhash_join_node.cpp

[Bug] Fix error result of left semi/anti join

---

be/src/exec/es/es_scroll_parser.cpp
be/src/exec/text_converter.hpp
be/src/exprs/runtime_filter.cpp
be/src/olap/row_block2.cpp
be/src/olap/rowset/segment_v2/column_reader.cpp
be/src/runtime/datetime_value.h
be/src/runtime/primitive_type.h
be/src/util/binary_cast.hpp
be/src/vec/core/types.h
be/src/vec/exec/join/vhash_join_node.cpp
be/src/vec/exec/vaggregation_node.cpp
be/src/vec/exec/vset_operation_node.cpp
be/src/vec/runtime/vdatetime_value.cpp
be/src/vec/runtime/vdatetime_value.h
be/src/vec/sink/mysql_result_writer.cpp

change some types from DateTimeValue to VecDateTimeValue
add a fun convert VecDateTimeValue to DateTimeValue

[Refactor] change some type from DateTimeValue to VecDateTimeValue

---

be/src/vec/CMakeLists.txt
be/src/vec/exprs/vexpr.cpp
be/src/vec/exprs/vinfo_func.cpp
be/src/vec/exprs/vinfo_func.h

Support info function in vectorized engine.

---

be/src/vec/core/block.h
be/src/vec/sink/vdata_stream_sender.cpp

[Refactor] Optimized the memory usage logic of sender and improved the performance in multi-threaded scenarios

---

be/src/vec/exec/join/vhash_join_node.cpp
be/src/vec/functions/functions_comparison.h

[Opt] Opt the join code and del unless compare code in vec datetime

---

be/src/vec/functions/function.h
gensrc/script/doris_builtins_functions.py

case as follows:
select * from tdate where date_format(`b`, '%Y%m')<'202200';
function date_format define is VARCHAR DATE_FORMAT(DATETIME date, VARCHAR format),
returnType is string,get_return_type(arguments) is nullable, its get_nested_type is string.
- [x ] Bugfix (non-breaking change which fixes an issue)
- [x ] Compiling and unit tests pass locally with my changes
If this is a relatively large or complex change, kick off the discussion at …

when execute date_format function, system will core

---

be/src/exec/exec_node.cpp
be/src/exec/schema_scan_node.h
be/src/runtime/datetime_value.h
be/src/vec/CMakeLists.txt
be/src/vec/exec/vschema_scan_node.cpp
be/src/vec/exec/vschema_scan_node.h
be/src/vec/functions/functions_comparison.h
be/src/vec/runtime/vdatetime_value.cpp
be/src/vec/runtime/vdatetime_value.h

Support vschema_scan_node.

---

be/src/exec/olap_scanner.cpp
be/src/olap/reader.h
be/src/olap/tablet_schema.cpp
be/src/olap/tablet_schema.h
be/src/olap/tuple_reader.cpp
be/src/vec/columns/column.h
be/src/vec/columns/column_complex.h
be/src/vec/columns/column_const.h
be/src/vec/columns/column_decimal.h
be/src/vec/columns/column_dummy.h
be/src/vec/columns/column_nullable.h
be/src/vec/columns/column_string.h
be/src/vec/columns/column_vector.h
be/src/vec/core/block.cpp
be/src/vec/core/block.h
be/src/vec/data_types/data_type.cpp
be/src/vec/data_types/data_type.h
be/src/vec/exec/volap_scanner.cpp
be/src/vec/olap/block_reader.cpp
be/src/vec/olap/block_reader.h
be/src/vec/olap/vcollect_iterator.cpp
be/src/vec/olap/vcollect_iterator.h

[Vec-Reader] Support unique table reader

---

be/src/exec/olap_scanner.cpp
be/src/olap/reader.h
be/src/vec/columns/column_nullable.cpp
be/src/vec/core/block.cpp
be/src/vec/core/block.h
be/src/vec/olap/block_reader.cpp
be/src/vec/olap/block_reader.h
be/src/vec/olap/vcollect_iterator.cpp
be/src/vec/olap/vcollect_iterator.h

[Opt] Remove unless shared_ptr call and inline some code

---

be/src/vec/core/block.cpp
be/src/vec/data_types/data_type_bitmap.h
be/src/vec/exec/join/vhash_join_node.cpp
be/src/vec/exec/vaggregation_node.cpp
be/src/vec/exec/vset_operation_node.cpp
be/src/vec/sink/vtabet_sink.cpp

[Bug] Fix the bug of DateTimeValue change to VecDateTimeValue

---

be/src/vec/olap/vcollect_iterator.cpp

[Bug] Fix the bug of reader duplicate key

---

be/src/vec/core/block.cpp

[Bug-Fix] Fix bug of load bitmap

---

be/src/vec/core/block.h

使用万能引用简化block里面的merge函数
逻辑如下：
由于万能引用在的值后续使用中会退化成左值
故 `template <typename T> void merge(T&& block)`得到的`block`是一个左值，
故 将原右值部分的`void merge(Block&& block) {xxx}`全部删除，保留原左值部分的实现。

use universal reference to simplify block function merge

---

be/src/olap/column_predicate.h
be/src/olap/null_predicate.cpp
be/src/olap/null_predicate.h

Support null predicate on vectorized engine.

[storage layer] Support null predicate

---

be/src/olap/block_column_predicate.cpp
be/src/olap/block_column_predicate.h
be/src/olap/column_predicate.h
be/src/olap/comparison_predicate.cpp
be/src/olap/comparison_predicate.h
be/src/vec/columns/predicate_column.h

参考 #238
这是存储层向量化的第二个pr，主要是对谓词框架加了新的接口

[storage layer] add new method for column

---

be/src/olap/column_predicate.h

- Fix column predicate causing compile failed
- Resolve code conflicts

[Compile] fix column predicate causing compile failed

---

be/src/olap/row_block2.cpp
be/src/vec/CMakeLists.txt
be/src/vec/aggregate_functions/aggregate_function.h
be/src/vec/aggregate_functions/aggregate_function_bitmap.h
be/src/vec/aggregate_functions/aggregate_function_hll_union_agg.h
be/src/vec/aggregate_functions/aggregate_function_min_max.cpp
be/src/vec/aggregate_functions/aggregate_function_min_max.h
be/src/vec/aggregate_functions/aggregate_function_null.h
be/src/vec/aggregate_functions/aggregate_function_reader.cpp
be/src/vec/aggregate_functions/aggregate_function_reader.h
be/src/vec/aggregate_functions/aggregate_function_simple_factory.cpp
be/src/vec/aggregate_functions/aggregate_function_simple_factory.h
be/src/vec/aggregate_functions/aggregate_function_sum.cpp
be/src/vec/aggregate_functions/aggregate_function_sum.h
be/src/vec/columns/column.h
be/src/vec/columns/column_complex.h
be/src/vec/columns/column_const.h
be/src/vec/columns/column_decimal.h
be/src/vec/columns/column_dummy.h
be/src/vec/columns/column_nullable.cpp
be/src/vec/columns/column_nullable.h
be/src/vec/columns/column_string.h
be/src/vec/columns/column_vector.h
be/src/vec/core/block.h
be/src/vec/core/column_with_type_and_name.cpp
be/src/vec/functions/function.h
be/src/vec/olap/block_reader.cpp
be/src/vec/olap/block_reader.h
be/src/vec/olap/vcollect_iterator.cpp
be/src/vec/olap/vcollect_iterator.h

--- null ---
unvectorized  500+ms
new agg clone 470+ms
unvectorized  380+ms
new uniq      260+ms
--- not null --- 
unvectorized  400+ms
new agg clone 290+ms
unvectorized 380+ms
new uniq     210+ms

[Feature] support agg reader

---

be/src/vec/exec/vcross_join_node.cpp

fix tpch Q11 result error: cross join lost the last block

---

be/src/vec/exec/vcross_join_node.cpp

fix bugs; if _left_block rows is 0, do not insert block

---

be/src/vec/exec/ves_http_scan_node.h
be/src/vec/exec/vexchange_node.cpp
be/src/vec/exec/vexchange_node.h
be/src/vec/exec/vmysql_scan_node.cpp
be/src/vec/exec/vmysql_scan_node.h
be/src/vec/exec/vschema_scan_node.h
be/src/vec/runtime/vpartition_info.cpp
be/src/vec/runtime/vpartition_info.h
be/src/vec/sink/vdata_stream_sender.cpp
be/test/vec/exprs/vexpr_test.cpp
be/test/vec/function/function_like_test.cpp

[Header]add header

---

be/src/vec/exec/vaggregation_node.cpp

when batch_size set smaller than rows, will cause memory out of bounds
- [ x] Bugfix (non-breaking change which fixes an issue)
- [ x] Compiling and unit tests pass locally with my changes

when batch_size set smaller than rows, will cause memory out of bounds

---

be/src/vec/exec/volap_scanner.cpp

[Bug] Fix the bug of volap_scanner filter

---

be/src/vec/exec/ves_http_scan_node.cpp
be/src/vec/exec/vschema_scan_node.cpp

add lost license header

---

be/src/exec/tablet_info.cpp
be/src/exec/tablet_info.h
be/src/exec/tablet_sink.cpp
be/src/exec/tablet_sink.h
be/src/vec/core/block.cpp
be/src/vec/core/block.h
be/src/vec/sink/vtabet_sink.cpp
be/src/vec/sink/vtablet_sink.h

[Vec Load] Support load

---

be/src/runtime/fold_constant_executor.cpp
be/src/runtime/fold_constant_executor.h
be/src/service/internal_service.cpp
fe/fe-core/src/main/java/org/apache/doris/rewrite/FoldConstantsRule.java

[Vec] Support vec fold constant

---

be/src/exec/tablet_sink.cpp
be/src/vec/columns/column.h
be/src/vec/columns/column_complex.h
be/src/vec/columns/column_const.h
be/src/vec/columns/column_decimal.h
be/src/vec/columns/column_dummy.h
be/src/vec/columns/column_nullable.h
be/src/vec/columns/column_string.h
be/src/vec/columns/column_vector.h
be/src/vec/functions/function_always_not_nullable.h
be/src/vec/functions/function_string_to_string.h
be/src/vec/functions/hll_cardinality.cpp
be/src/vec/functions/hll_hash.cpp
be/src/vec/olap/block_reader.cpp
be/src/vec/olap/block_reader.h
be/src/vec/olap/vcollect_iterator.cpp
be/src/vec/olap/vcollect_iterator.h

[Bug] make some hll function is always not nullable implement && fix string replace

---

be/src/exec/tablet_info.cpp
be/src/olap/row_block2.cpp
be/src/runtime/raw_value.h
be/src/vec/aggregate_functions/aggregate_function_min_max.h
be/src/vec/exec/join/vhash_join_node.cpp
be/src/vec/exec/vaggregation_node.cpp
be/src/vec/exec/vanalytic_eval_node.cpp
be/src/vec/sink/vdata_stream_sender.cpp

[Bug] Fix some bug of load / analytic / join / scan / bucket shuffle

---

be/src/exec/tablet_info.cpp
be/src/olap/row_block2.cpp
be/src/runtime/primitive_type.h
be/src/runtime/raw_value.h
be/src/vec/aggregate_functions/aggregate_function_min_max.h
be/src/vec/exec/join/vhash_join_node.cpp
be/src/vec/exec/vaggregation_node.cpp
be/src/vec/exec/vanalytic_eval_node.cpp
be/src/vec/exprs/vectorized_fn_call.cpp
be/src/vec/exprs/vin_predicate.cpp
be/src/vec/exprs/vin_predicate.h
be/src/vec/functions/function_bitmap.cpp
be/src/vec/functions/function_case.h
be/src/vec/functions/function_ifnull.h
be/src/vec/functions/function_string.h
be/src/vec/functions/in.cpp
be/src/vec/functions/like.cpp
be/src/vec/olap/block_reader.cpp
be/src/vec/sink/vdata_stream_sender.cpp
fe/fe-core/src/main/java/org/apache/doris/analysis/InPredicate.java

[Bug] Fix the core bug and support in_iter and refactor of in predicate

---

be/src/vec/columns/predicate_column.h

Fix compile error when try to instantiate predicate_column

Fix compile error when try to instantiate predicate_column

---

be/src/vec/functions/modulo.cpp
fe/fe-core/src/main/java/org/apache/doris/analysis/ArithmeticExpr.java

[Expr] Fix bug of arithmetic expr and support fmod in it

---

be/src/vec/functions/function_case.h

1 通过gcc和clang编译
2 通过sql正确性测试 ```SELECT SUM(CASE WHEN LO_SUPPLYCOST + 10000 > 100000 then 1 else 0 END) FROM lineorder_flat;```

[Clang Compile] Fix clang compile failed in function_case

---

be/src/vec/common/arena.h

[Clang Compile]Fix arena.h clang complie failed

---

be/src/exec/exec_node.cpp
be/src/vec/CMakeLists.txt
be/src/vec/exec/vassert_num_rows_node.cpp
be/src/vec/exec/vassert_num_rows_node.h

[Exec] Support Vec AssertNumRowsNode

---

be/src/vec/CMakeLists.txt
be/src/vec/functions/comparison_equal_for_null.cpp
be/src/vec/functions/nullif.cpp
be/src/vec/functions/simple_function_factory.h
be/src/vec/utils/util.hpp

[Function] Support eq_for_null function

---

be/src/exec/exec_node.cpp
be/src/exec/exec_node.h
be/src/runtime/plan_fragment_executor.cpp
be/src/runtime/plan_fragment_executor.h
be/src/vec/core/block.cpp
be/src/vec/core/block.h
be/src/vec/exec/join/vhash_join_node.cpp
be/src/vec/exec/vaggregation_node.cpp
be/src/vec/exec/vblocking_join_node.cpp
be/src/vec/exec/vcross_join_node.cpp
be/src/vec/exec/vset_operation_node.cpp
be/src/vec/exprs/vectorized_agg_fn.cpp
be/src/vec/functions/comparison_equal_for_null.cpp
be/src/vec/functions/function.cpp
be/src/vec/sink/vtabet_sink.cpp
be/src/vec/utils/util.hpp

2. Delete unless code in low cardinatily string in function which cause block copy
3. Release unless memmory of column mem from function exectue
If this is a relatively large or complex change, kick off the discussion at dev@doris.apache.org by explaining why you chose the solution you did and what alternatives you …

[Opt] 1. Change the map in Block to phmap

---

be/src/exec/olap_scanner.cpp
be/src/olap/reader.cpp
be/src/olap/reader.h
be/src/vec/olap/block_reader.cpp
be/src/vec/olap/block_reader.h
be/src/vec/olap/vcollect_iterator.cpp

[Bug] fix reader init fail

---

be/src/vec/aggregate_functions/aggregate_function.h
be/src/vec/aggregate_functions/aggregate_function_min_max.cpp
be/src/vec/aggregate_functions/aggregate_function_min_max.h
be/src/vec/aggregate_functions/aggregate_function_window.cpp
be/src/vec/aggregate_functions/aggregate_function_window.h
be/src/vec/exec/vanalytic_eval_node.cpp
be/src/vec/exec/vanalytic_eval_node.h
be/src/vec/exec/vset_operation_node.cpp
fe/fe-core/src/main/java/org/apache/doris/analysis/AnalyticExpr.java
fe/fe-core/src/main/java/org/apache/doris/catalog/AggregateFunction.java
fe/fe-core/src/main/java/org/apache/doris/catalog/FunctionSet.java

Fix error about first/last value

[Bug] Fix error about first/last value

---

be/CMakeLists.txt
thirdparty/build-thirdparty.sh

Fix compile bug during compile thirdparty and during link stage

Fix compile bug: cyrus sasl build error

---

be/src/vec/core/block.cpp
be/src/vec/functions/function.cpp

[Opt] Vec the code of null map

---

be/src/vec/sink/vdata_stream_sender.cpp

fix stream_sender null data judgement

---

be/src/vec/aggregate_functions/aggregate_function_reader.cpp
be/src/vec/aggregate_functions/aggregate_function_reader.h
be/src/vec/aggregate_functions/aggregate_function_simple_factory.cpp
be/src/vec/aggregate_functions/aggregate_function_window.cpp
be/src/vec/aggregate_functions/aggregate_function_window.h

[Feature] support replace and replace_if_not_null

---

be/src/vec/columns/predicate_column.h

[Codestyle] refact predicate column

---

be/CMakeLists.txt
be/src/exec/exec_node.cpp
be/src/exec/exec_node.h
be/src/exec/text_converter.hpp
be/src/vec/aggregate_functions/aggregate_function_count.h
be/src/vec/aggregate_functions/aggregate_function_window.h
be/src/vec/core/block.cpp
be/src/vec/core/block.h
be/src/vec/data_types/number_traits.h
be/src/vec/exec/join/vhash_join_node.cpp
be/src/vec/exec/vaggregation_node.cpp
be/src/vec/exec/vanalytic_eval_node.cpp
be/src/vec/exec/vcross_join_node.cpp
be/src/vec/exec/ves_http_scan_node.cpp
be/src/vec/exec/vexcept_node.cpp
be/src/vec/exec/vintersect_node.cpp
be/src/vec/exec/vmysql_scan_node.cpp
be/src/vec/exec/vodbc_scan_node.cpp
be/src/vec/exec/volap_scan_node.cpp
be/src/vec/exec/vschema_scan_node.cpp
be/src/vec/exec/vselect_node.cpp
be/src/vec/exec/vset_operation_node.h
be/src/vec/exec/vsort_node.cpp
be/src/vec/exec/vunion_node.cpp
be/src/vec/functions/comparison_equal_for_null.cpp
be/src/vec/functions/function_date_or_datetime_to_string.h
be/src/vec/functions/functions_comparison.h
fe/fe-core/src/main/java/org/apache/doris/analysis/Analyzer.java
fe/fe-core/src/main/java/org/apache/doris/analysis/TableRef.java

[Refactor] Support Reach Limit in all Exec Node && Fix error result
